export const ADD_MODAL_OPEN = "ADD_MODAL_OPEN";
export const EDIT_MODAL_OPEN = "EDIT_MODAL_OPEN";
export const DELETE_MODAL_OPEN = "DELETE_MODAL_OPEN";
export const MODAL_FUNCTION_START = "MODAL_FUNCTION_START";
export const MODAL_FUNCTION_SUCCESS = "MODAL_FUNCTION_SUCCESS";
export const MODAL_CLOSE = "MODAL_CLOSE";